///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Konfigurator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the KonfiguratorRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("e71fbbc8-6324-4cdd-a132-933bc9564b13")]
    public partial class KonfiguratorRepository : RepoGenBaseFolder
    {
        static KonfiguratorRepository instance = new KonfiguratorRepository();
        KonfiguratorRepositoryFolders.CARATAppFolder _carat;
        KonfiguratorRepositoryFolders.KonfiguratorDropDownAppFolder _konfiguratordropdown;
        KonfiguratorRepositoryFolders.Konfigurator_upperLeftAppFolder _konfigurator_upperleft;
        KonfiguratorRepositoryFolders.KonfDOMAppFolder _konfdom;

        /// <summary>
        /// Gets the singleton class instance representing the KonfiguratorRepository element repository.
        /// </summary>
        [RepositoryFolder("e71fbbc8-6324-4cdd-a132-933bc9564b13")]
        public static KonfiguratorRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public KonfiguratorRepository() 
            : base("KonfiguratorRepository", "/", null, 0, false, "e71fbbc8-6324-4cdd-a132-933bc9564b13", ".\\RepositoryImages\\KonfiguratorRepositorye71fbbc8.rximgres")
        {
            _carat = new KonfiguratorRepositoryFolders.CARATAppFolder(this);
            _konfiguratordropdown = new KonfiguratorRepositoryFolders.KonfiguratorDropDownAppFolder(this);
            _konfigurator_upperleft = new KonfiguratorRepositoryFolders.Konfigurator_upperLeftAppFolder(this);
            _konfdom = new KonfiguratorRepositoryFolders.KonfDOMAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e71fbbc8-6324-4cdd-a132-933bc9564b13")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The CARAT folder.
        /// </summary>
        [RepositoryFolder("d8e2174b-d9ed-4df4-9d5b-c051b79a26ef")]
        public virtual KonfiguratorRepositoryFolders.CARATAppFolder CARAT
        {
            get { return _carat; }
        }

        /// <summary>
        /// The KonfiguratorDropDown folder.
        /// </summary>
        [RepositoryFolder("a7d2c34a-5449-4661-950f-b04727986d16")]
        public virtual KonfiguratorRepositoryFolders.KonfiguratorDropDownAppFolder KonfiguratorDropDown
        {
            get { return _konfiguratordropdown; }
        }

        /// <summary>
        /// The Konfigurator_upperLeft folder.
        /// </summary>
        [RepositoryFolder("1ce84f55-8dd6-4e15-96a5-496ee52b5a17")]
        public virtual KonfiguratorRepositoryFolders.Konfigurator_upperLeftAppFolder Konfigurator_upperLeft
        {
            get { return _konfigurator_upperleft; }
        }

        /// <summary>
        /// The KonfDOM folder.
        /// </summary>
        [RepositoryFolder("296bfdc6-7684-4eed-9bb6-f18fa038fab0")]
        public virtual KonfiguratorRepositoryFolders.KonfDOMAppFolder KonfDOM
        {
            get { return _konfdom; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class KonfiguratorRepositoryFolders
    {
        /// <summary>
        /// The CARATAppFolder folder.
        /// </summary>
        [RepositoryFolder("d8e2174b-d9ed-4df4-9d5b-c051b79a26ef")]
        public partial class CARATAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _herstellerInfo;
            RepoItemInfo _konfiguratorInfo;

            /// <summary>
            /// Creates a new CARAT  folder.
            /// </summary>
            public CARATAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CARAT", "/form[@title>'CARAT']", parentFolder, 30000, null, true, "d8e2174b-d9ed-4df4-9d5b-c051b79a26ef", "")
            {
                _herstellerInfo = new RepoItemInfo(this, "Hersteller", "?/?/toolbar[@accessiblename=' ']/?/?/tabpage[@accessiblename='Hersteller']", ".//tabpage[@accessiblename='Hersteller']", 30000, null, "4f311918-f59d-4043-863b-1849b5f84bab");
                _konfiguratorInfo = new RepoItemInfo(this, "Konfigurator", "?/?/toolbar[@accessiblename=' ']/toolbar[@accessiblename='Hersteller']/?/?/button[@accessiblename='Konfigurator']", ".//button[@accessiblename='Konfigurator']", 30000, null, "c0660434-4c59-4d68-b327-6d6d5a9f99b4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d8e2174b-d9ed-4df4-9d5b-c051b79a26ef")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d8e2174b-d9ed-4df4-9d5b-c051b79a26ef")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Hersteller item.
            /// </summary>
            [RepositoryItem("4f311918-f59d-4043-863b-1849b5f84bab")]
            public virtual Ranorex.TabPage Hersteller
            {
                get
                {
                    return _herstellerInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Hersteller item info.
            /// </summary>
            [RepositoryItemInfo("4f311918-f59d-4043-863b-1849b5f84bab")]
            public virtual RepoItemInfo HerstellerInfo
            {
                get
                {
                    return _herstellerInfo;
                }
            }

            /// <summary>
            /// The Konfigurator item.
            /// </summary>
            [RepositoryItem("c0660434-4c59-4d68-b327-6d6d5a9f99b4")]
            public virtual Ranorex.Button Konfigurator
            {
                get
                {
                    return _konfiguratorInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Konfigurator item info.
            /// </summary>
            [RepositoryItemInfo("c0660434-4c59-4d68-b327-6d6d5a9f99b4")]
            public virtual RepoItemInfo KonfiguratorInfo
            {
                get
                {
                    return _konfiguratorInfo;
                }
            }
        }

        /// <summary>
        /// The KonfiguratorDropDownAppFolder folder.
        /// </summary>
        [RepositoryFolder("a7d2c34a-5449-4661-950f-b04727986d16")]
        public partial class KonfiguratorDropDownAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new KonfiguratorDropDown  folder.
            /// </summary>
            public KonfiguratorDropDownAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KonfiguratorDropDown", "/form[@title='Konfigurator']/dom[@domain='']//button[#'dropdownMenuButton']", parentFolder, 30000, null, true, "a7d2c34a-5449-4661-950f-b04727986d16", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a7d2c34a-5449-4661-950f-b04727986d16")]
            public virtual Ranorex.Button Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a7d2c34a-5449-4661-950f-b04727986d16")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The Konfigurator_upperLeftAppFolder folder.
        /// </summary>
        [RepositoryFolder("1ce84f55-8dd6-4e15-96a5-496ee52b5a17")]
        public partial class Konfigurator_upperLeftAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Konfigurator_upperLeft  folder.
            /// </summary>
            public Konfigurator_upperLeftAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Konfigurator_upperLeft", "/form[@title='Konfigurator']/?/?/menuitem[@accessiblename='Systemmenü']", parentFolder, 30000, null, true, "1ce84f55-8dd6-4e15-96a5-496ee52b5a17", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1ce84f55-8dd6-4e15-96a5-496ee52b5a17")]
            public virtual Ranorex.MenuItem Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1ce84f55-8dd6-4e15-96a5-496ee52b5a17")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The KonfDOMAppFolder folder.
        /// </summary>
        [RepositoryFolder("296bfdc6-7684-4eed-9bb6-f18fa038fab0")]
        public partial class KonfDOMAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new KonfDOM  folder.
            /// </summary>
            public KonfDOMAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KonfDOM", "/form[@title='Konfigurator']/dom", parentFolder, 30000, null, false, "296bfdc6-7684-4eed-9bb6-f18fa038fab0", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("296bfdc6-7684-4eed-9bb6-f18fa038fab0")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("296bfdc6-7684-4eed-9bb6-f18fa038fab0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
