///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Konfigurator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateDOM recording.
    /// </summary>
    [TestModule("fe5f2a50-ad91-4d7b-9213-c1119cffb8be", ModuleType.Recording, 1)]
    public partial class ValidateDOM : ITestModule
    {
        /// <summary>
        /// Holds an instance of the KonfiguratorRepository repository.
        /// </summary>
        public static KonfiguratorRepository repo = KonfiguratorRepository.Instance;

        static ValidateDOM instance = new ValidateDOM();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateDOM()
        {
            expectedURL = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateDOM Instance
        {
            get { return instance; }
        }

#region Variables

        string _expectedURL;

        /// <summary>
        /// Gets or sets the value of variable expectedURL.
        /// </summary>
        [TestVariable("5f4f0ad6-c1df-448d-9cff-6ebffa017863")]
        public string expectedURL
        {
            get { return _expectedURL; }
            set { _expectedURL = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (domain=$expectedURL) on item 'KonfDOM'.", repo.KonfDOM.SelfInfo, new RecordItemIndex(0));
                Validate.AttributeEqual(repo.KonfDOM.SelfInfo, "domain", expectedURL, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
